name = "HalfIntegers"
uuid = "f0d1745a-41c9-11e9-1dd9-e5d34d218721"
authors = ["Sebastian Stock"]
version = "0.1.3"

[compat]
julia = "0.7, 1"

[extras]
SaferIntegers = "88634af6-177f-5301-88b8-7819386cfa38"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["SaferIntegers", "Test"]
